using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Linq;
using TerbinLibrary;
using TerbinLibrary.Data;
using TerbinLibrary.SteamFarlands;
using TerbinLibrary.TerbinServiceHelper.Exceptions;
using TerbinLibrary.Useful;
using TerbinLibrary.Useful.Nodes;

namespace TerbinService.Managers;
/*
 -- Variables:
  empieza: _ = es privada NO local.
  empieza: minuscula = es privada local.
  empieza: "p"en minuscula = parametro entrante local.
  empieza: mayuscula = publica.
 -- Funciones:
  empieza: mayusculas = publica.
  empieza: minusculas = privada.
 */


public static partial class Manager
{
    /// <summary>
    /// ___________________( Español )___________________<br />
    /// Subclase estática dedicada a la gestión, instalación y manipulación de los juegos o su directorio base dentro de las instancias locales.<br />
    /// Encargada de clonar y retirar instalaciones coordinando los reportes de progreso y verificando el control de versión.<br />
    /// Notas: Todas las operaciones devuelven un código de status propio.<br />
    /// Tips: Si necesitas interactuar con instancias desde el exterior utiliza los Handlers en su lugar.<br />
    /// ___________________( English )___________________<br />
    /// Static subclass dedicated to the management, installation, and manipulation of games or their base directory within local instances.<br />
    /// Responsible for cloning and removing installations by coordinating progress reports and verifying version control.<br />
    /// Notes: All operations return a specific status code.<br />
    /// Tips: If you need to interact with instances from outside, use the Handlers instead.<br />
    /// </summary>
    public static class Games
    {
        /// <summary>
        /// ___________________( Español )___________________<br />
        /// Manejador para envolver el comportamiento de clonado en instancia aportando inicialización al feedback de progreso hacia el cliente.<br />
        /// Notas: Conecta la id de petición (Request) al comunicador activo.<br />
        /// Tips: Ideal para ser llamado desde los servicios web o IPC del Worker.<br />
        /// ___________________( English )___________________<br />
        /// Handler to wrap the instance cloning behavior providing initialization to the progress feedback towards the client.<br />
        /// Notes: Connects the Request ID directly to the active communicator.<br />
        /// Tips: Ideal to be called from the worker's web services or IPC layer.<br />
        /// </summary>
        /// <param name="pPathDir">Es: Ruta fuente donde reside el juego base a clonar. <br />En: Source directory where the base game resides to clone.</param>
        /// <param name="pNameInstance">Es: Nombre de la instancia objetivo. <br />En: Target instance name.</param>
        /// <param name="pIdRequest">Es: Identificador de la petición generada por el comunicador. <br />En: Request identifier generated by the communicator.</param>
        /// <param name="pOverwrite">Es: Booleano que indica si se sobrescriben los archivos destino. <br />En: Boolean indicating whether to overwrite destination files.</param>
        /// <param name="pCancellationToken">Es: Token para detener asíncronamente la tarea. <br />En: Token to cancel the task asynchronously.</param>
        /// <returns>Es: Un indicador enumerable Status delimitando el final de la rutina. <br />En: An enumerable Status indicating the end of the routine.</returns>
        [Obsolete]
        public static async Task<InternalErrors> HandleCloneInInstance
            (string pPathDir, string pNameInstance, ushort pIdRequest, bool pOverwrite, CancellationToken pCancellationToken = default)
        {
            var progress = ProgressUtil.CreateProgessBarr(Worker.CurrentContext.Value.Communicator, pIdRequest);

            return await CloneInInstance(pPathDir, pNameInstance, pOverwrite, progress, pCancellationToken);
        }



        /// <summary>
        /// ___________________( Español )___________________<br />
        /// Toma un directorio existente y lo vuelca enteramente dentro de una instancia, elaborando los registros locales (handwritten) y descubriendo el ejecutable principal.<br />
        /// Notas: Modifica subarchivos manifiesto. En caso de ser cancelada, invoca una autolimpieza a sí misma.<br />
        /// Tips: Es un proceso largo y de alto IO de disco, evite usar sin barra de carga.<br />
        /// ___________________( English )___________________<br />
        /// Takes an existing directory and fully dumps it into an instance, producing local handwritten logs and discovering the main executable.<br />
        /// Notes: Mutates internal manifest files. If cancelled, it performs self-cleaning on the partial instance.<br />
        /// Tips: It's a long process with high disk I/O, avoid using without a progress bar.<br />
        /// </summary>
        /// <param name="pPathDir">Es: Origen de copiado del juego. <br />En: Source copying path for the game.</param>
        /// <param name="pNameInstance">Es: Instancia en la cual depositar la información. <br />En: Instance in which to deposit the information.</param>
        /// <param name="pOverwrite">Es: Permitir el reemplazo en colisiones en disco. <br />En: Allow replacement on disk collisions.</param>
        /// <param name="pProgrss">Es: Objeto referencial que recibe reportes de progreso Terbin. <br />En: Reference object handling Terbin progress reports.</param>
        /// <param name="pCancellationToken">Es: Token interno para abortar. <br />En: Internal token to safely abort.</param>
        /// <returns>Es: Resultado Status dictaminando el éxito o el código de fallo específico. <br />En: Status result declaring success or specific failure code.</returns>
        public static async Task<InternalErrors> CloneInInstance
            (string pPathDir, string pNameInstance, bool pOverwrite, IProgress<TerbinInfoProgrss>? pProgrss = default, CancellationToken pCancellationToken = default)
        {
            string? pathInstace = Manager.Instances.GetPathFolder(pNameInstance);
            if (string.IsNullOrEmpty(pathInstace))
                return InternalErrors.InstanceGet;

            if (Manager.Instances.ThereGameByPath(pathInstace))
                return InternalErrors.GameAlredyExist;

            // if (!Manager.Instances.IsInstance(pathInstace))
            //     return Status.ErrorNotIsInstance;

            if (pCancellationToken.IsCancellationRequested)
                return InternalErrors.IsCancelled;

            var (status, json) = await NodeUtil.CloneDirectory(pPathDir, pathInstace, pOverwrite, pProgrss, pCancellationToken);
            if (status != StatusNodeUtil.Succes)
                return InternalErrors.IsUnknown;

            Manager.Manifest.WriteHandwritten(pathInstace, json);

            if (pCancellationToken.IsCancellationRequested)
            {
                await RemoveInInstance(pNameInstance, pCancellationToken: CancellationToken.None);
                return InternalErrors.IsCancelled;
            }
                
            List<string> exes = NodeUtil.GetAllExeFiles(pathInstace);
            if (exes.Count > 0)
            {
                //return Status.ErrorGameNotExes;

                var update = Manager.Manifest.UpdateInstaceByPath(pathInstace, manifest =>
                {
                    manifest.Executable = Path.GetRelativePath(pathInstace, exes[0]);
                    manifest.Version = Games.GetVersion();
                });
                if (!update)
                {
                    // TODO: Desclonar.
                    return InternalErrors.ManifestUpdate;
                }
            }

            if (pCancellationToken.IsCancellationRequested)
            {
                await RemoveInInstance(pNameInstance, pCancellationToken: CancellationToken.None);
                return InternalErrors.IsCancelled;
            }

            return InternalErrors.IsSucces;
        }


        /// <summary>
        /// ___________________( Español )___________________<br />
        /// Envoltorio orquestador que inicia el proceso de eliminación del juego en una instancia publicando estatus con IProgress.<br />
        /// Notas: Configura el Tracker para informar a lo largo del proceso del gestor IPC.<br />
        /// Tips: Úselo siempre por sobre el método base a menos que no haya red.<br />
        /// ___________________( English )___________________<br />
        /// Orchestrator wrapper that triggers the game deletion process on an instance, publishing status with IProgress.<br />
        /// Notes: Sets up the tracker to report heavily along the IPC manager flow.<br />
        /// Tips: Prefer this over the base method unless networking is missing.<br />
        /// </summary>
        /// <param name="pNameInstance">Es: Referencia textual de qué instancia será limpiada. <br />En: Text reference to which instance will be cleared.</param>
        /// <param name="pIdRequest">Es: Número de solicitud activa del pool al cliente. <br />En: Active request number tracked by the client pool.</param>
        /// <param name="pCancellationToken">Es: Control de interrupción de sub-bloque. <br />En: Sub-block interruption control.</param>
        /// <returns>Es: Bandera enum Status indicando si todo fue exitoso. <br />En: Status enum flag of success bounds.</returns>
        [Obsolete]
        public static async Task<InternalErrors> HandleRemoveInInstance
            (string pNameInstance, ushort pIdRequest, CancellationToken pCancellationToken = default)
        {
            var progress = ProgressUtil.CreateProgessBarr(Worker.CurrentContext.Value.Communicator, pIdRequest);

            return await RemoveInInstance(pNameInstance, progress, pCancellationToken);
        }

        /// <summary>
        /// ___________________( Español )___________________<br />
        /// Purgador de archivos alojados utilizando la memoria del log de volcado (Handwritten).<br />
        /// Notas: Garantiza no romper la integridad de los manifiestos cruzados y deshace el borrado lógico al éxito.<br />
        /// Tips: Tenga precaución dado que este borrado físico es irreversible.<br />
        /// ___________________( English )___________________<br />
        /// Hosted files purger utilizing the dump log memory (Handwritten).<br />
        /// Notes: Safeguards cross-manifest integrity and unfolds logical removals on success.<br />
        /// Tips: Exercise caution since this physical deletion is strictly irreversible.<br />
        /// </summary>
        /// <param name="pNameInstance">Es: Sujeto objetivo del formato en disco. <br />En: Target subject assigned for disk formatting.</param>
        /// <param name="pProgress">Es: Contenedor que recibirá los ticks del borrado de cada fichero. <br />En: Container receiving ticks upon each file deletion.</param>
        /// <param name="pCancellationToken">Es: Aborto condicional de lectura de ficheros. <br />En: Conditional file reading boot abortion.</param>
        /// <returns>Es: Código de terminación (Succes = 1). <br />En: Termination code (Succes = 1).</returns>
        public static async Task<InternalErrors> RemoveInInstance
            (string pNameInstance, IProgress<TerbinInfoProgrss>? pProgress = default, CancellationToken pCancellationToken = default)
        {
            string? pathInstace = Instances.GetPathFolder(pNameInstance);
            if (string.IsNullOrEmpty(pathInstace))
                return InternalErrors.InstanceGet;

            var handwritten = Manager.Manifest.GetHandwritten(pathInstace);

            if (handwritten == null)
                return InternalErrors.HandwrittenGet;

            if (pCancellationToken.IsCancellationRequested)
                return InternalErrors.IsCancelled;

            // Teoricamente DeleteFromHandwritten no puede fallar.
            var r = NodeUtil.DeleteFromHandwritten(pathInstace, handwritten, pProgress);

            bool removeHand = Manager.Manifest.RemoveHandwritten(pathInstace);
            if (!removeHand)
                return InternalErrors.HandwrittenRemove;

            var update = Manager.Manifest.UpdateInstaceByPath(pathInstace, manifest =>
            {
                manifest.Executable = "";
                manifest.Version = "";
            });
            if (!update)
                return InternalErrors.ManifestUpdate;

            return InternalErrors.IsSucces;
        }


        public static bool RunOfInstance(string pNameInstance)
        {



            return true;
        }


        [TODO("Comprobar si es Linux")]
        public static bool Run(string pPath)
        {

            return ManagerFarlands.LaunchGame(pPath);
        }


        /// <summary>
        /// ___________________( Español )___________________<br />
        /// Intermediario puramente estético para extraer la versión subyacente del base de datos o gestor Farlands.<br />
        /// Notas: Actúa como puente genérico de metadatos.<br />
        /// Tips: Llamarlo evita usar una referencia externa en módulos donde no corresponda.<br />
        /// ___________________( English )___________________<br />
        /// Purely aesthetic middleware extracting the underlying version from the database or Farlands manager.<br />
        /// Notes: Acts as generic metadata bridge layout.<br />
        /// Tips: Calling this prevents unwanted outside references inside rigid modules.<br />
        /// </summary>
        /// <returns>Es: Un string con la versión ensamblada. <br />En: A string wrapping the full assembly version.</returns>
        public static string GetVersion()
        {
            return ManagerFarlands.GetVersion();
        }
    }
}
